name: HelpItem
version: 0.1.8
author: PhilipGrabow
softdepend: [PermissionsEx]

main: de.philipgrabow.helpitem.Main

commands:
  helpitem:
    description: Erzeugt das Item zur Hilfe
    aliases: [helpitem, hi]
    permission: helpitem.create.self
    usage: /<command>
  applybook:
    description: Erzeugt das Hilfebuch
    aliases: [abook, applybook]
    usage: /<command> [help|confirm]
permissions:
  helpitem.*:
    description: All Access
    default: op
    children:
      - helpitem.create.self: true
      - helpitem.heal: op
      - helpitem.hunger: op
      - helpitem.kill: op
      - helpitem.openinventory: op
      - helpitem.mitglied: op
      - helpitem.owner: op
      - helpitem.playermenue.*: op
      - helpitem.helpbook.help: op
  helpitem.create.self:
    description: Du kannst dir das Item erzeugen!
    default: true
  helpitem.heal:
    description: Berechtigung zum Heilen
    default: op
  helpitem.hunger:
    description: Berechtigung zum Hunger stillen
    default: op
  helpitem.kill:
    description: Berechtigung zum Killen
    default: op
  helpitem.openinventory:
    description: Berechtigung zum Inventar
    default: op
  helpitem.mitglied:
    description: Macht dich zum Mitglied
    default: op
  helpitem.owner:
    description: Macht dich zum Owner
    default: op
  helpitem.helpbook.*:
    descriprion: HilfeBuch
    default: op
    children:
      - helpitem.helpbook.help: op
      - helpitem.helpbook.confirm: op
  helpitem.playermenue.*:
    description: All Access to Playermenue
    default: op
    children:
      - helpitem.playermenue.hunger: op
      - helpitem.playermenue.heal: op
      - helpitem.playermenue.invclear: op
      - helpitem.playermenue.gm0: op
      - helpitem.playermenue.gm1: op
      - helpitem.playermenue.gm2: op
      - helpitem.playermenue.gm3: op
      - helpitem.playermenue.tele: op
  helpitem.playermenue.hunger:
    description: Berechtigt zum Spieler hunger stillen
    default: op
  helpitem.playermenue.heal:
    description: Berechtigt zum Spieler heilen
    default: op
  helpitem.playermenue.invclear:
    description: Berechtigt zum Inventar leeren
    default: op
  helpitem.playermenue.gm0:
    description: Berechtigt fuer Gamemode 0
    default: true
  helpitem.playermenue.gm1:
    description: Berechtigt fuer Gamemode 1
    default: op
  helpitem.playermenue.gm2:
    description: Berechtigt fuer Gamemode 2
    default: op
  helpitem.playermenue.gm3:
    description: Berechtigt fuer Gamemode 3
    default: op
  helpitem.playermenue.tele:
    description: Zeigt Koordinaten und teleportiert dich
    default: op